repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: README.md
    -   id: check-added-large-files
        exclude: README.md
    -   id: check-yaml
        exclude: README.md
    -   id: check-json
        exclude: launch.json
    -   id: check-case-conflict
        exclude: README.md
    -   id: check-merge-conflict
        exclude: README.md
    -   id: double-quote-string-fixer
        exclude: README.md
    -   id: end-of-file-fixer
        exclude: README.md

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: (__init__.py|alembic/versions)
        args: [ --profile, black, --filter-files, --src-path, app]


-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        args: [--max-line-length=120, --in-place]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: (__init__.py|alembic/versions)
        args: ["--max-line-length=120"]
