version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    volumes:
      - shops_db:/var/lib/postgresql/data/
    env_file:
      - .env

  shops:
    image: avnosov/shops:v1
    command: >
      sh -c "
        poetry run alembic upgrade head &&
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 80
      "
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    env_file:
      - .env

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  shops_db:
