version: '3.8'

services:

  test_db:
    image: postgres:15.1-alpine
    volumes:
      - test-shop_db:/var/lib/postgresql/data/
    env_file:
      - .env

  tests:
    image: avnosov/shop-test:v1
    command: poetry run pytest
    depends_on:
      -  test_db
    env_file:
      - .env

volumes:
  test-shop_db:
