name: shops workflow

on: [push]

jobs:

  tests:
    name: flake8 and pytest tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install project dependencies from local pyproject.toml
      run: |
        cd ./.
        poetry install
    - name: Test with flake8 and django tests
      run: |
        poetry run python -m flake8 --ignore=N805
        # pytest
